export function getBrowserShellElements(documentObject = globalThis.document) {
  return {
    selectFolderBtn: documentObject.getElementById('selectFolderBtn'),
    restoreFolderBtn: documentObject.getElementById('restoreFolderBtn'),
    refreshFolderBtn: documentObject.getElementById('refreshFolderBtn'),
    cancelTaskBtn: documentObject.getElementById('cancelTaskBtn'),
    toggleVisibleBtn: documentObject.getElementById('toggleVisibleBtn'),
    clearSelectionBtn: documentObject.getElementById('clearSelectionBtn'),
    profileNameInput: documentObject.getElementById('profileNameInput'),
    profileSelect: documentObject.getElementById('profileSelect'),
    saveProfileBtn: documentObject.getElementById('saveProfileBtn'),
    loadProfileBtn: documentObject.getElementById('loadProfileBtn'),
    deleteProfileBtn: documentObject.getElementById('deleteProfileBtn'),
    selectedRepositoryName: documentObject.getElementById('selectedRepositoryName'),
    scanPhaseText: documentObject.getElementById('scanPhaseText'),
    statusMessage: documentObject.getElementById('statusMessage'),
    selectedSizeText: documentObject.getElementById('selectedSizeText'),
    selectedLinesText: documentObject.getElementById('selectedLinesText'),
    visibleRowsText: documentObject.getElementById('visibleRowsText'),
    largestFilesSummary: documentObject.getElementById('largestFilesSummary'),
    largestFilesList: documentObject.getElementById('largestFilesList'),
    filterInput: documentObject.getElementById('filterInput'),
    ignorePatternsInput: documentObject.getElementById('ignorePatternsInput'),
    ignorePatternsStatus: documentObject.getElementById('ignorePatternsStatus'),
    treeSummaryText: documentObject.getElementById('treeSummaryText'),
    treeList: documentObject.getElementById('treeList'),
    includePreamble: documentObject.getElementById('includePreamble'),
    preambleInput: documentObject.getElementById('preambleInput'),
    includeGoal: documentObject.getElementById('includeGoal'),
    goalInput: documentObject.getElementById('goalInput'),
    removeCommentsToggle: documentObject.getElementById('removeCommentsToggle'),
    minifyOutputToggle: documentObject.getElementById('minifyOutputToggle'),
    selectionReviewFiles: documentObject.getElementById('selectionReviewFiles'),
    selectionReviewSize: documentObject.getElementById('selectionReviewSize'),
    selectionReviewTokens: documentObject.getElementById('selectionReviewTokens'),
    selectionReviewWarnings: documentObject.getElementById('selectionReviewWarnings'),
    selectionLargestSelectedList: documentObject.getElementById('selectionLargestSelectedList'),
    selectionTypeBreakdown: documentObject.getElementById('selectionTypeBreakdown'),
    selectionDirectoryBreakdown: documentObject.getElementById('selectionDirectoryBreakdown'),
    guardrailWarningKbInput: documentObject.getElementById('guardrailWarningKbInput'),
    guardrailConfirmationKbInput: documentObject.getElementById('guardrailConfirmationKbInput'),
    combineBtn: documentObject.getElementById('combineBtn'),
    clearOutputBtn: documentObject.getElementById('clearOutputBtn'),
    reloadAppBtn: documentObject.getElementById('reloadAppBtn'),
    outputFileNameInput: documentObject.getElementById('outputFileNameInput'),
    copyOutputBtn: documentObject.getElementById('copyOutputBtn'),
    downloadOutputBtn: documentObject.getElementById('downloadOutputBtn'),
    saveOutputBtn: documentObject.getElementById('saveOutputBtn'),
    outputSummaryText: documentObject.getElementById('outputSummaryText'),
    outputTextarea: documentObject.getElementById('outputTextarea'),
    copyDiagnosticsBtn: documentObject.getElementById('copyDiagnosticsBtn'),
    clearDiagnosticsBtn: documentObject.getElementById('clearDiagnosticsBtn'),
    diagnosticsLog: documentObject.getElementById('diagnosticsLog')
  };
}

export const getShellElements = getBrowserShellElements;
